---
github:
  prebuilds:
    addBadge: true
    addComment: false
    addCheck: false
    master: true
    branches: true
    pullRequestsFromForks: true


image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - nimsaem.nimvscode
...
