---
name: run_nimpretty

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  format_code_with_nimpretty:
    name: format code with nimpretty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: jiro4989/setup-nim-action@v1
      
      - name: Run nimpretty
        run: |
          ./run_nimpretty.sh

      - name: Fail if needs reformatting
        run: |
          if [[ `git status --porcelain` ]]; then
             echo "please reformat these files with nimpretty:"
             git status --porcelain=v1
             cat init.sh
             pwd
             exit 1
          fi
...
